name: blg604final
dependencies:
  - python>=3.5
  - pytorch==1.5.0
  - pip:
    - --find-links https://download.pytorch.org/whl/torch_stable.html
    - torchvision==0.6.0      
    - gym==0.15.4                                            
    - msgpack-rpc-python==0.4.1
    - jsonpickle==1.4.1
    - matplotlib==3.1.3
    - msgpack-python==0.5.6
    - numpy==1.18.1
    - pylint==2.4.4
    - scipy==1.4.1
    - tornado==4.5.3