name: final604
dependencies:
  - python>=3.5
  - pip:
    - gym==0.15.4      
    - tornado==4.5.3      
    - msgpack-python==0.5.6                                
    - msgpack-rpc-python==0.4.1
    - jsonpickle==1.4.1
    - numpy==1.18.1
    - scipy==1.4.1
